#!/usr/bin/env python3
"""Parse external review files and produce a summary table.

Reads review markdown files generated by run_reviews.py, extracts scores,
verdicts, and boolean checks via regex, and outputs a structured summary.

Usage:
  python scripts/parse_reviews.py                        # Latest reviews
  python scripts/parse_reviews.py --date 2026-05-15      # Specific date
  python scripts/parse_reviews.py --baseline 2026-05-10  # Before/after comparison
  python scripts/parse_reviews.py --json                 # Machine-readable output
"""

import argparse
import json
import re
import sys
from pathlib import Path
from datetime import date

BASE = Path("C:/PROJECTS/SHELL")


def parse_single_review(path: Path) -> dict:
    """Extract all scored fields from one review file."""
    text = path.read_text(encoding="utf-8")
    result = {
        "file": str(path),
        "desk_verdict": None,
        "dimensions": {},
        "booleans": {},
        "composite": None,
        "min_score": None,
        "final_verdict": None,
        "human_authorship": None,
        "auto_fail": None,
    }

    # Desk rejection gate
    desk_match = re.search(r'\*\*Verdict:\*\*\s*(SEND_FOR_REVIEW|DESK_REJECT)', text)
    if desk_match:
        result["desk_verdict"] = desk_match.group(1)

    # D1-D15 scores — look for "SCORE: N" pattern
    score_sections = re.findall(
        r'\*\*D(\d{1,2})\.\s+[^*]+\*\*.*?(?:SCORE|Score):\s*(\d+)',
        text, re.DOTALL
    )
    for dim_num, score in score_sections:
        result["dimensions"][f"D{dim_num}"] = int(score)

    # B1-B12 verdicts — look for "Verdict:" followed by UPPER_CASE_STRING
    bool_sections = re.findall(
        r'\*\*B(\d{1,2})\.\s+[^*]+\*\*.*?[Vv]erdict:?\s*\*?\*?\s*([A-Z][A-Z_]+)',
        text, re.DOTALL
    )
    for bool_num, verdict in bool_sections:
        result["booleans"][f"B{bool_num}"] = verdict

    # Weighted composite score
    comp_match = re.search(r'[Ww]eighted\s+[Cc]omposite\s*[=≈]\s*(\d+\.?\d*)', text)
    if comp_match:
        result["composite"] = float(comp_match.group(1))

    # Minimum score
    min_match = re.search(r'[Mm]inimum\s+[Ss]core.*?=\s*(\d+)', text)
    if min_match:
        result["min_score"] = int(min_match.group(1))

    # Auto-fail
    af_match = re.search(r'[Aa]uto.?[Ff]ail\s+[Tt]riggered\??\s*=?\s*(YES|NO|Yes|No)', text)
    if af_match:
        result["auto_fail"] = af_match.group(1).upper() == "YES"

    # Final verdict — handles both "**Verdict**\n**ACCEPT**" and "**Verdict:** ACCEPT"
    verdict_match = re.search(
        r'Research Quality Verdict.*?(?:\*\*|:\s*)([A-Z][A-Z_]+)',
        text, re.DOTALL
    )
    if verdict_match:
        result["final_verdict"] = verdict_match.group(1)

    # Human authorship assessment
    auth_match = re.search(
        r'Human Authorship Assessment.*?(?:\*\*|:\s*)([A-Z][A-Z_]+)',
        text, re.DOTALL
    )
    if auth_match:
        result["human_authorship"] = auth_match.group(1)

    return result


def discover_reviews(date_str: str | None = None) -> dict:
    """Find all review files, grouped by paper slug and model.

    Returns: {slug: {model_name: Path}}
    """
    papers_dir = BASE / "papers"
    results = {}

    for paper_dir in sorted(papers_dir.iterdir()):
        if not paper_dir.is_dir():
            continue
        reviews_dir = paper_dir / "reviews"
        if not reviews_dir.exists():
            continue

        slug = paper_dir.name
        results[slug] = {}

        # Find review files matching pattern
        for review_file in sorted(reviews_dir.iterdir()):
            if not review_file.name.endswith(".md"):
                continue

            # Match: Model_review_YYYY-MM-DD.md or Model_runN_review_YYYY-MM-DD.md
            match = re.match(r'^(.+?)_review_(\d{4}-\d{2}-\d{2})\.md$', review_file.name)
            if not match:
                continue

            model_name = match.group(1)
            file_date = match.group(2)

            # Skip legacy lowercase files (gemini, gpt, grok — old v1 format)
            if model_name in ("gemini", "gpt", "grok"):
                continue

            if date_str and file_date != date_str:
                continue

            # If no date filter, take the latest
            if date_str is None:
                if model_name in results[slug]:
                    # Keep the newer one
                    existing_date = re.search(r'\d{4}-\d{2}-\d{2}', results[slug][model_name].name)
                    if existing_date and file_date >= existing_date.group(0):
                        results[slug][model_name] = review_file
                else:
                    results[slug][model_name] = review_file
            else:
                results[slug][model_name] = review_file

    # Remove empty entries
    return {k: v for k, v in results.items() if v}


def format_summary_table(parsed: dict) -> str:
    """Format parsed results as a markdown summary table."""
    lines = []
    lines.append("# Review Summary\n")

    # Master verdict table
    lines.append("## Verdicts & Composites\n")
    lines.append("| Paper | Model | Verdict | Composite | Min | AI (B1) | Citations (B3) | Human Auth |")
    lines.append("|-------|-------|---------|-----------|-----|---------|----------------|------------|")

    for slug in sorted(parsed.keys()):
        for model in sorted(parsed[slug].keys()):
            r = parsed[slug][model]
            verdict = r.get("final_verdict", "N/A")
            composite = f"{r['composite']:.2f}" if r.get("composite") else "N/A"
            min_s = str(r.get("min_score", "N/A"))
            ai = r.get("booleans", {}).get("B1", "N/A")
            cit = r.get("booleans", {}).get("B3", "N/A")
            auth = r.get("human_authorship", "N/A")
            short_slug = slug.split("_2026")[0]
            lines.append(f"| {short_slug} | {model} | {verdict} | {composite} | {min_s} | {ai} | {cit} | {auth} |")

    lines.append("")

    # Dimension scores table
    lines.append("## Dimension Scores (D1-D15)\n")
    dims = [f"D{i}" for i in range(1, 16)]
    header = "| Paper | Model | " + " | ".join(dims) + " |"
    sep = "|-------|-------| " + " | ".join(["---"] * 15) + " |"
    lines.append(header)
    lines.append(sep)

    for slug in sorted(parsed.keys()):
        for model in sorted(parsed[slug].keys()):
            r = parsed[slug][model]
            scores = [str(r.get("dimensions", {}).get(d, "-")) for d in dims]
            short_slug = slug.split("_2026")[0]
            lines.append(f"| {short_slug} | {model} | " + " | ".join(scores) + " |")

    lines.append("")
    return "\n".join(lines)


def flag_disagreements(parsed: dict, threshold: int = 3) -> list[str]:
    """Find cross-model disagreements > threshold on any dimension."""
    flags = []

    for slug in sorted(parsed.keys()):
        models = list(parsed[slug].keys())
        if len(models) < 2:
            continue

        for i in range(len(models)):
            for j in range(i + 1, len(models)):
                m1, m2 = models[i], models[j]
                r1 = parsed[slug][m1]
                r2 = parsed[slug][m2]

                for dim in [f"D{k}" for k in range(1, 16)]:
                    s1 = r1.get("dimensions", {}).get(dim)
                    s2 = r2.get("dimensions", {}).get(dim)
                    if s1 is not None and s2 is not None:
                        delta = abs(s1 - s2)
                        if delta > threshold:
                            short_slug = slug.split("_2026")[0]
                            flags.append(
                                f"  {short_slug} {dim}: {m1}={s1}, {m2}={s2} (delta={delta})"
                            )

    return flags


def compare_baselines(current: dict, baseline: dict) -> str:
    """Compare current scores against a baseline run."""
    lines = []
    lines.append("## Before/After Comparison\n")
    lines.append("| Paper | Model | Baseline Verdict | Current Verdict | Baseline Comp | Current Comp | Delta |")
    lines.append("|-------|-------|-----------------|-----------------|---------------|--------------|-------|")

    for slug in sorted(current.keys()):
        if slug not in baseline:
            continue
        for model in sorted(current[slug].keys()):
            if model not in baseline.get(slug, {}):
                continue
            curr = current[slug][model]
            base = baseline[slug][model]
            bv = base.get("final_verdict", "N/A")
            cv = curr.get("final_verdict", "N/A")
            bc = base.get("composite")
            cc = curr.get("composite")
            bc_str = f"{bc:.2f}" if bc else "N/A"
            cc_str = f"{cc:.2f}" if cc else "N/A"
            delta = f"{cc - bc:+.2f}" if (bc and cc) else "N/A"
            short_slug = slug.split("_2026")[0]
            lines.append(f"| {short_slug} | {model} | {bv} | {cv} | {bc_str} | {cc_str} | {delta} |")

    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Parse external review files.")
    parser.add_argument("--date", type=str, default=None,
                       help="Review date to parse (YYYY-MM-DD). Default: latest.")
    parser.add_argument("--baseline", type=str, default=None,
                       help="Baseline date for before/after comparison.")
    parser.add_argument("--json", action="store_true",
                       help="Output machine-readable JSON.")
    parser.add_argument("--threshold", type=int, default=3,
                       help="Disagreement threshold for flagging (default: 3).")
    args = parser.parse_args()

    # Discover and parse current reviews
    reviews = discover_reviews(args.date)
    if not reviews:
        print(f"No reviews found" + (f" for date {args.date}" if args.date else ""))
        return 1

    parsed = {}
    for slug, models in reviews.items():
        parsed[slug] = {}
        for model, path in models.items():
            parsed[slug][model] = parse_single_review(path)

    if args.json:
        print(json.dumps(parsed, indent=2, default=str))
        return 0

    # Format and print summary
    summary = format_summary_table(parsed)
    print(summary)

    # Flag disagreements
    flags = flag_disagreements(parsed, args.threshold)
    if flags:
        print(f"## Cross-Model Disagreements (>{args.threshold} points)\n")
        for f in flags:
            print(f)
        print()

    # Baseline comparison
    if args.baseline:
        baseline_reviews = discover_reviews(args.baseline)
        baseline_parsed = {}
        for slug, models in baseline_reviews.items():
            baseline_parsed[slug] = {}
            for model, path in models.items():
                baseline_parsed[slug][model] = parse_single_review(path)
        comparison = compare_baselines(parsed, baseline_parsed)
        print(comparison)

    # Save summary
    reviews_dir = BASE / "reviews"
    reviews_dir.mkdir(exist_ok=True)
    date_str = args.date or date.today().isoformat()
    summary_path = reviews_dir / f"summary_{date_str}.md"
    with open(summary_path, "w", encoding="utf-8") as f:
        f.write(summary)
        if flags:
            f.write(f"\n## Cross-Model Disagreements (>{args.threshold} points)\n\n")
            for flag in flags:
                f.write(f"{flag}\n")
    print(f"\nSummary saved to: {summary_path}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
